### ISSUE TITLE
python 3.5, eppy 0.5.41 error when using getedges

### ISSUE THREAD

**Issue by kostovmike** [santoshphilip/eppy#130]
I've installed eppy 0.5.41 but again I'm finding difficulties using the 'getedges'  function.
I had to manually download usefull_scripts folder from github and copy it into the eppy folder.

#below is my code
from eppy.modeleditor import IDF
from eppy import hvacbuilder
from io import StringIO
from eppy import modeleditor
from eppy import walk_hvac
from eppy.useful_scripts import loopdiagram

iddfile = "/Users/kostovmike/Desktop/MY-PYTHON/myeppy/Energy+.idd"
IDF.setiddname(iddfile)
fname = "/Users/kostovmike/Desktop/MY-PYTHON/myeppy/PlantApplicationsGuide_Example2.idf"
idf1 = IDF(fname)

edges = loopdiagram.getedges(fname, iddfile)
#end of script

After I run the above script I get the fowling error:
...
...
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py", line 494, in getedges
    data, commdct = readidf.readdatacommdct(fname, iddfile=iddfile)

ValueError: too many values to unpack (expected 2)

**Comment by santoshphilip** [comment]
I'll take a look. 

Loop diagram was written along time back. 
(Actually written in desperation, because I had to see the loop to fix my model :-)

If this is not an easy fix, it might take some time for me to get into the code. 
Most of the system and loop code is written in an ad-hoc manner, because the documentation on how a loop is structured is poor or non-existent.  One has to look thru the example files and do a lot of detective work. 

I am not strong on the systems and plants part of energyplus. 
In the big picture I should collaborate with someone who is more familiar (an expert?) on systems and plants.  Any volunteers?

**Comment by jamiebull1** [comment]
This looks like the same issue where we're not picking up the third return
value. Not sure if fixing that will get back to the same problem though.

For what it's worth, I've used `loopdiagram` on some pretty complex layouts
without any trouble so you've obviously done a pretty good job of it,
Santosh!

**Comment by jamiebull1** [comment]
@santoshphilip Yes, it's the same issue as the previous one. I should really have picked it up when I fixed that. I'll raise another PR once the last CI tests have passed on my fork.

As far as the ad-hoc nature of the `loopdiagram` script, I don't think it's too bad. I had to pick it apart a little, and DRY it out a bit to make it more testable but it's fairly clear what it's doing.

I'm happy to volunteer to break it up a bit more and document it a bit more thoroughly though. It's relevant to the next stage of my research, so I can easily justify spending the time on `loopdiagram` and also on `hvacbuilder`.

**Comment by santoshphilip** [comment]
yes ! I would be happy to work with you on `loopdiagram` and `hvacbuilder`

**Comment by jamiebull1** [comment]
It's a deal!

**Comment by jamiebull1** [comment]
Updated PR #130
