### ISSUE TITLE
Problems using run() method

### ISSUE THREAD

**Issue by fsofelipe** [santoshphilip/eppy#157]
Hello guys, first of all, I'm new to this project, I just heard about it last week and I'm so excited about the new possibilities this will open to my college project.

So, since I'm new using the Eppy environment I have being facing some difficulties. 
The first of all I still cannot use the method run(). I have no idea why, but just importing the function cause me an error. 
`Python 3.5.2 (default, Nov 17 2016, 17:05:23) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from eppy.runner import IDF5
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'IDF5'
`

I have tried to use conda and create an environment for Eppy, just like someone suggested in another issue (sorry but I do not remember who said it), and I still got the same error.

Thanks for the comprehension.

**Comment by jamiebull1** [comment]
Hi @fsofelipe , glad you see some potential in this.

A couple of things:

First, at the moment we only support running EnergyPlus version 8.5, though hopefully that will be fixed in the next day or so.

Second, you should just be able to call `idf.run()` on your IDF object. `IDF5` doesn't exist any more in the current version. Do we have some out of date documentation somewhere that needs fixing?

In any case, this is the code you should be using to run a job:

        from eppy.modeleditor import IDF

        iddfile = "path to the v8.5 IDD file"
        fname = "path to your IDF"
        epw = "path to your EPW file"
        IDF.setiddname(iddfile)
        idf = IDF(fname1, epw)
        idf.run()

Hope that helps, and let me know if there's any other issues.

**Comment by fsofelipe** [comment]
Hello, @jamiebull1 ,
Thank you for your fast replay,
I will try the example that you just gave me, the only problem my IDF file is written using 8.4 version and I have no idea how to update it. 
And about your question, there still is part of the documentation using IDF5 [http://pythonhosted.org/eppy/newfunctions.html](url), "Running EnergyPlus from Eppy".  Also I may have seeing IDF6 too somewhere that I don't remember exactly. 

In addition to my first question, I already have another one, but I am not sure if it is part or it will be part of the project in a future. Anyway, in my problem I have the challenge  to interact with the simulation, providing value to the status of openings from my IDF and get weather data from it. Is that possible using Eppy or will it be implemented in a future?

**Comment by jamiebull1** [comment]
To update it, install EnergyPlus 8.5 from [here](https://github.com/NREL/EnergyPlus/releases/tag/v8.5.0).

Then on Windows at least, you go to something `C:/EnergyPlusV8-5-0/PreProcess/IDFVersionUpdater` and launch `IDFVersionUpdater.exe` and follow the instructions. I'm not sure, but I would expect there's something similar on linux systems.

Thanks for pointing to the outdated docs. I'll get that fixed.

On your final question, do you mean interacting with a run while it's processing? If so that's not something we've considered, and I'm not sure it's possible. You might want to look at BCVTB.

**Comment by santoshphilip** [comment]
@fsofelipe , if you wait a day or so. I'll release the new version with the fix that will run any version of E+
@jamiebull1 , I'll update the documentation. It is generated from a python notebook, so directly editing the *.rst file is not the way to go. (I have not yet documented how to go from notebook -> restructured text -> html/sphinx)

**Comment by jamiebull1** [comment]
@santoshphilip ok, great. Want me to write the words?

**Comment by santoshphilip** [comment]
The original narrative is pretty good. I'll update it to match the new code.

**Comment by santoshphilip** [comment]
aargh !!! I am in merge hell with the documentation

**Comment by santoshphilip** [comment]
released r0.5.44 fixing above issues. Available at pypi for pip install
