### ISSUE TITLE
Import to grasshopper fails

### ISSUE THREAD

**Issue by mostaphaRoudsari** [santoshphilip/eppy#162]
@santoshphilip [this is](https://github.com/MahmoudAbdelRahman/GH_CPython) the project that I mentioned. @MahmoudAbdelRahman has been working on it and it has a great potential to get projects like eppy to Grasshopper with no pain. It uses CPython and not IronPython.

**Comment by MahmoudAbdelRahman** [comment]
Thanks so much  @mostaphaRoudsari  !

**Comment by santoshphilip** [comment]
@mostaphaRoudsari It was great talking to you yesterday.Triggered a lot of new ideas. Thanks for pointing me to [GH_CPython](https://github.com/MahmoudAbdelRahman/GH_CPython)  

@yiyuan1840 this may resolve our problem tring to import eppy into Grasshopper (refered to in issue #147 ) GH_CPython uses CPython instead of IronPython. If you are still working on this can you try it out.

@MahmoudAbdelRahman I have a question for you. Is it possible to run python3 code in GH_CPython ? I am starting to write most of my code in python3, and I am hoping it will slip into grasshopper easily. (It is not a problem for eppy, since eppy will run in python2 and python3)

**Comment by MahmoudAbdelRahman** [comment]
Hi @santoshphilip , 
So far, it can run python 3.x if it is the only version installed, but I'll make a separated Gh_CPython3.x and upload it along.

**Comment by santoshphilip** [comment]
@ncbrown  can you test by importing eppy into [GH_CPython](https://github.com/MahmoudAbdelRahman/GH_CPython). Post here if any issues arise.

**Comment by MahmoudAbdelRahman** [comment]
Hi @santoshphilip, 
I have added a new feature for Gh_CPython, that is, choosing the favorite Python interpreter e.g. Python27, Python34, Python35 ... and so on. by clicking on the blue line at the bottom of any component a new window will popup, where you can specify the preferred python.exe . as shown below: 
![image](https://user-images.githubusercontent.com/6969514/29244139-5b7eebd4-7fb1-11e7-9d4d-43b9f6fdfe67.png)

**Comment by santoshphilip** [comment]
thanks @MahmoudAbdelRahman 

We are a little slow on testing this, but we are getting there.
If this works out, it is quite a force multiplier.

**Comment by MahmoudAbdelRahman** [comment]
Thanks so much @santoshphilip, 
It will be my great pleasure to contribute to this. 
![image](https://user-images.githubusercontent.com/6969514/29263420-f9995782-80d8-11e7-88cf-a5c673f5a1dd.png)

**Comment by santoshphilip** [comment]
@MahmoudAbdelRahman , You are the man !

It clearly does work.

**Comment by ncbrown** [comment]
works for me too. thank you @MahmoudAbdelRahman and @mostaphaRoudsari !

**Comment by santoshphilip** [comment]
I am going to leave this issue open until I add this to the documentation

**Comment by santoshphilip** [comment]
Documentation has been added to show how to run eppy in grasshopper (in the Installation section of the documentation)

This update is now in the develop branch. It will come out in the next release
