### ISSUE TITLE
Errors when opening two EnergyPlus example files

### ISSUE THREAD

**Issue by JasonGlazer** [santoshphilip/eppy#257]
Errors occur when trying to open the following example files that come with EnergyPlus 9.1.0 with eppy:

ASHRAE9012016_OutPatientHealthCare_Denver.idf
ConstSpeedBranchPumpExercise.idf'

I was using eppy 0.5.51 with Python 3.7.4

**Comment by milagrossanz** [comment]
Hello everyone! I'm jumping on this opened issue, as I came across the same problem. 

@santoshphilip when you say that this can be fixed by updating the idd file" do you mean manually?

Because I've tried adding the fields to the object in the Energy+.idd and the Energy+V8_9_0.idd (this is the version I'm working with) by opening the files in a notepad and it doesn't seem to work. I mean, the same NoIDDFieldsError pops up. 

This is the code and the error, just in case I'm missing something:

```
import sys

pathnameto_eppy = 'C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy'
sys.path.append(pathnameto_eppy)

from eppy.modeleditor import IDF

iddfile = "C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy/resources/iddfiles/Energy+V8_9_0_2.idd"
fname1="C:/Users/milag/Desktop/Leire/F.idf"

IDF.setiddname(iddfile)
idf = IDF(fname1)
idf.epw='ESP_Bilbao.08250_SWEC.epw'

idf.run(
        output_directory="C:/Users/milag/Desktop/Leire",
        output_prefix="F2",
)

```

```
26 <class 'int'> 1 <class 'int'>
26 <class 'int'>
ext, lastvars 1 ['A19']
['A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27', 'A28', 'A29', 'A30', 'A31', 'A32', 'A33', 'A34', 'A35', 'A36', 'A37', 'A38', 'A39', 'A40', 'A41', 'A42', 'A43', 'A44', 'A45']
---------------------------------------------------------------------------

NoIDDFieldsError                          Traceback (most recent call last)

<ipython-input-1-e05cd849679e> in <module>
     10 
     11 IDF.setiddname(iddfile)
---> 12 idf = IDF(fname1)
     13 idf.epw='ESP_Bilbao.08250_SWEC.epw'
     14 

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\modeleditor.py in __init__(self, idfname, epw)
    546         if idfname != None:
    547             self.idfname = idfname
--> 548             self.read()
    549         if epw != None:
    550             self.epw = epw

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\modeleditor.py in read(self)
    671             raise IDDNotSetError(errortxt)
    672         readout = idfreader1(
--> 673             self.idfname, self.iddname, self, commdct=self.idd_info, block=self.block
    674         )
    675         (self.idfobjects, block, self.model, idd_info, idd_index, idd_version) = readout

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\idfreader.py in idfreader1(fname, iddfile, theidf, conv, commdct, block)
    305     iddgaps.missingkeys_nonstandard(block, commdct, dtls, nofirstfields)
    306     # bunchdt = makebunches(data, commdct)
--> 307     bunchdt = makebunches_alter(data, commdct, theidf, block)
    308     return bunchdt, block, data, commdct, idd_index, versiontuple
    309 

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\idfreader.py in makebunches_alter(data, commdct, theidf, block)
    107         list1 = []
    108         for obj in objs:
--> 109             bobj = makeabunch(commdct, obj, obj_i, block=block)
    110             list1.append(bobj)
    111         bunchdt[key] = Idf_MSequence(list1, objs, theidf)

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\idfreader.py in makeabunch(commdct, obj, obj_i, debugidd, block)
     80             # print(errortext)
     81             print(extlst)
---> 82             raise NoIDDFieldsError(errortext)
     83     return bobj
     84 

NoIDDFieldsError: idfobject with key 'WATERUSE:CONNECTIONS' & first field 'Grupo de Salida de Agua' has 46 fields while the idd for 'WATERUSE:CONNECTIONS' has only 20 fields. Add the following fields to the object 'WATERUSE:CONNECTIONS' in file Energy+.idd 'A20, A21, A22, A23, A24, A25, A26, A27, A28, A29, A30, A31, A32, A33, A34, A35, A36, A37, A38, A39, A40, A41, A42, A43, A44, A45;'

```

**Comment by santoshphilip** [comment]
just making sure that you added to the right `idd` file. You mention three files.
1. Because I've tried adding the fields to the object in the Energy+.idd 
2. and the Energy+V8_9_0.idd (this is the version I'm working with) 
3. iddfile = "C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy/resources/iddfiles/Energy+V8_9_0_2.idd"
    - iddfile in 3. is in your code

From your code, `eppy` is using "C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy/resources/iddfiles/Energy+V8_9_0_2.idd". So try making you changes there.

If it still doesn't work, post your idd-change here <include a few lines before and after the change>. There is a chance you put the semi-colon (;) in the wrong place.

**Comment by milagrossanz** [comment]
Sorry for the confusion, I was actually mentioning and modifying only two idd files. 
I renamed the 2nd to "Energy+V8_9_0_2.idd" after I modified it. 

Thanks for your help, @santoshphilip. Your comment about the semicolon made me realize my mistake. The idd didn't seem to be updating because I added the fields after the semicolon, so it didn't make much difference.

**Comment by santoshphilip** [comment]
In the best of worlds, `eppy` should automatically make that change to the `idd`.

There is not much motivation to make that change,  since the `Energy+.idd` is being phased out and replaced with `Energy+.schema.epJSON` files. 

At one point EnergyPlus will no longer use the `idd` file. The new `Energy+.schema.epJSON` file does not have this issue of not having enough fields - it works differently. 

I am going to close this issue. Open it again if you still run into problems.
