### ISSUE TITLE
readhtml and fasthtml not working

### ISSUE THREAD

**Issue by Chandangsharma** [santoshphilip/eppy#333]
[PKNSOffice_3Table.zip](https://github.com/santoshphilip/eppy/files/6324120/PKNSOffice_3Table.zip)
Attached EnergyPlus output file (PKNSOffice_3Table.html) can not be read either through readhtml and fasthtml. Can anyone please suggest workaround for this issue?

**Comment by TfedUD** [comment]
import pandas as pd

tables = pd.read_html('table_data.html')
print('Tables found:', len(tables))
df1 = tables[0] # Save first table in variable df1
df2 = tables[1] # Saving next table in variable df2

print('First Table')
print(df1)
print('Another Table')
print(df2)



https://stackabuse.com/reading-and-writing-html-tables-with-pandas/

**Comment by Chandangsharma** [comment]
Thanks @TfedUD . Tried the above solution. Program gets stuck forever in line tables = pd.read_html('table_data.html').
Can you run the html file or suggest any other workaround? Thanks again.

**Comment by santoshphilip** [comment]
Wow ! That is a large file 27.8 MB and 70,000 lines.
My browser is not able to open it
I can open it in a text editor.

I can see `readhtml` breaking, since it tries to load the file into memory.
I would expect `fasthtml` to work, since it reads the file a line at a time.

Can you post the code you used for `fasthtml` that did not work. I'll try to see what is going on.

**Comment by santoshphilip** [comment]
My browser finally opened it. It took some time.

**Comment by Chandangsharma** [comment]
Thanks @santoshphilip . Please find the `fasthtml` code in the attachment. readhtml and fasthtml both are not working. Thanks for any inputs.
[read_html.zip](https://github.com/santoshphilip/eppy/files/6328648/read_html.zip)

**Comment by santoshphilip** [comment]
I updated your code. It works now.

readhtml and fasthtml take different arguments.
This is not clear in the documentation. 

Please raise any questions about the updated code. I want to use your response as a way of improving the documentation

    # Python program to caculate Overall Thermal Transfer sub_value (OTTV) using EnergyPlus

    import os
    import sys
    from eppy.results import readhtml, fasthtml # the eppy module with functions to read the html
    from datetime import date
    # import pandas as pd

    pathnameto_eppy = '../'
    sys.path.append(pathnameto_eppy)

    class OTTVClass:   
      
        # init method or constructor    
        def __init__(self):   
            iddfile = "C:\\EnergyPlusV8-9-0\\Energy+.idd"

        def getOutput(self):
            file_name = "PKNSOffice_3Table.html" #idfname.replace('.idf', 'Table.html')
            file_handle = open(file_name, 'r') # get a file handle to the html file

            heat_transfer = fasthtml.tablebyname(file_handle, "HeatTransfer Surface")
            print(heat_transfer)
            file_handle = open(file_name, 'r') # get a file handle to the html file
            exterior_fenestration = fasthtml.tablebyname(file_handle, 'Exterior Fenestration')
            print(exterior_fenestration)
            file_handle = open(file_name, 'r') # get a file handle to the html file
            exterior_door = fasthtml.tablebyname(file_handle, 'Exterior Door')
            print(exterior_door)

    # Create the root window 
    o = OTTVClass()
    o.getOutput()
    exit()

**Comment by Chandangsharma** [comment]
@santoshphilip New code is working. Thanks. It is really slow though. Maybe be that is the limitation of python reading large html files. Could you please point what was changed in the new code?

**Comment by santoshphilip** [comment]
fasthtml.tablebyname takes file_handle as an argument
Your code was reading the file_handle before sending it to fasthtml.tablebyname()
You were misled because readhtml needs text as the argument. So you have to do a read() before calling the readhtel function

another thing to note is that the file_handle created each time fasthtml.tablebyname is called.
This is because fasthtml.tablebyname exhausts file_handle every time it is called. (meaning, it reaches the end of the file)

I hope this makes sense. I was typing fast just before turing in for the night.

fasthtml was faster than my browser (Safari on a mac) in reading the file. You file is humongous. Nothing can read it fast.
Take a look at the fasthtml code. It does a lazy evaluation - so it is able to read a file of any size. If the file is too large readhtml will crash and burn, but fastthml will work no matter how large the file is.
