### ISSUE TITLE
readhtml

### ISSUE THREAD

**Issue by amaliahicks** [santoshphilip/eppy#36]
Hi there,

I'm trying to process output data and have been having trouble using named_grid_h on the ABUPS End Uses Summary.  The error I'm getting is

ValueError: Field names cannot start with an underscore '_'

I'm wondering if it has something to with the blank 2nd to last row of the table that has values u'\xa0'?  

In general I would really like to read the output tables into numpy or pandas DataFrame arrays, but I don't seem to be experienced enough in python coding to pull that off smoothly  :)

Thanks much!
Amalia

**Comment by eayoungs** [comment]
Amalia,
I've got an updated approach to this project that I think might improve speed and versatility. I put up a gist of the code here:
https://gist.github.com/eayoungs/0b6e0db5f28e1848582e

I just finished the code to zip all the tables into a dictionary so that they can be referred to directly by name. I will be working on looping this code to iterate over all the files and allow selection of individual tables across all files by name. I'd love to hear what you think.

Happy Memorial Day!

Eric
