### ISSUE TITLE
Make the Quiet Mode Actually Quiet

### ISSUE THREAD

**Issue by DimitrisMantas** [santoshphilip/eppy#364]
Hello everyone,

Whenever I use run(..., verbose="q"), the output to the console is actually `EnergyPlus Completed Successfully.`

This is potentially unwanted behavior in cases where one might use eppy in conjunction with another program that also prints stuff to the console. For example, if you're running E+ multiple times with different .IDF files to optimize a specific variable, then you might need to print relevant metrics at specific time intervals. However, if eppy is constantly printing to the console, the stuff that actually matters is obscured by the `EnergyPlus Completed Successfully.` messages.

Thanks.

**Comment by santoshphilip** [comment]
@DimitrisMantas , Can you take a look at the code and see if there is an easy way to turn this off
OR redirect it to a separate log file.

You can make a pull request or let us know your findings

**Comment by DimitrisMantas** [comment]
Hi, @santoshphilip,

Thank you for immediate response!

I'll be sure to take a look at the issue.

**Comment by santoshphilip** [comment]
I did some testing with the code in your pull request.
It works fine (I like how you have coded it)

I discovered that the older versions of E+ (8.5 for instance) do not print out the line `EnergyPlus Completed Successfully`.   I am going to merge your pull request. See further comments at the pull request #365

You opened this issue for a specific use case that you had.
it would be good to capture this knowledge in the user documentation so others can benefit from it

Maybe we have a section called

## Running verbose, quiet or silent - is it a submarine ?

explaining why we need silent. 
Best if you explain it, since you ran into it.

Once we wrap up this issue I'll open a new issue to update to the user documentation with the new section

**Comment by DimitrisMantas** [comment]
Sure, I completely agree with updating the documentation to reflect the proposed changes and can definitely write something up. Where should I post it?

**Comment by santoshphilip** [comment]
@DimitrisMantas I referred to this issue in unmethours.com
https://unmethours.com/question/64004/is-it-possible-to-remove-the-energy-plus-simulation-log-while-running-it-from-eppy/

You can respond in unmethours.com with an answer (solution: is your pull request)

Shall we close this issue. (You should do the closing). A new issue can be opened if documentation is critical

**Comment by DimitrisMantas** [comment]
Alright. I'll be closing the issue and will keep a heads up to write some relevant documentation in case the proposed changees make it into the main branch at some point.

**Comment by santoshphilip** [comment]
Once it gets into the develop branch, it will get into the master branch for sure :-)
    On Saturday, December 4, 2021, 08:43:19 AM PST, Dimitris Mantas ***@***.***> wrote:  
 
 


Alright. I'll be closing the issue and will keep a heads up to write some relevant documentation in case the proposed changees make it into the main branch at some point.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by santoshphilip** [comment]
@DimitrisMantas , I am glad to see that the changes you made are useful to other people, 
unmet hours is an interesting forum. It is like [Stackexchange.com](https://stackoverflow.com) 

See this question on https://stackoverflow.com about python lists comprehension.
https://stackoverflow.com/questions/51861577/python-list-function-or-list-comprehension/51861670

There are comments and answers. 
The answers become reference for the future. People will do google search and will arrive at the answer. I wanted you to write an answer to the problem in such a way that it would help someone who is reading it two or three years in the future. Since you solved this problem, you should own the answer.

I takes time to compose a good answer. You can take your time composing a good response/answer. You can also edit it later to make it better. At the moment, there is enough information for the person to solve his problem, so there is no hurry to post the answer
