### ISSUE TITLE
error in main module

### ISSUE THREAD

**Issue by mohammad-zeyad** [santoshphilip/eppy#378]
the code is 

import sys

pathnameto_eppy = "C:/Users/USER/AppData/Local/Programs/Python/venv/Lib/site-packages/eppy"
sys.path.append(pathnameto_eppy)
from eppy import modeleditor
from eppy.modeleditor import IDF
iddfile = "C:/Users/USER/AppData/Local/Programs/Python/venv/Lib/site-packages/eppy/resources/iddfiles/Energy+V8_9_0.idd"
fname1 = "C:/Users/USER/AppData/Local/Programs/Python/venv/Lib/site-packages/eppy/resources/idffiles/V_8_9/test1.idf"
IDF.setiddname(iddfile)
idf1 = IDF(fname1)

idf1.printidf()

after running my program it shows 

C:\Users\USER\AppData\Local\Programs\Python\venv\Scripts\python.exe C:/Users/USER/AppData/Local/Programs/Python/venv
C:\Users\USER\AppData\Local\Programs\Python\venv\Scripts\python.exe: can't find '__main__' module in 'C:/Users/USER/AppData/Local/Programs/Python/venv' 

Please help me to solve this issue

**Comment by santoshphilip** [comment]
Can you show me the program you ran. 


    On Monday, March 14, 2022, 07:44:16 AM PDT, Mohammad Zeyad ***@***.***> wrote:  
 
 


after running my program it shows

C:\Users\USER\AppData\Local\Programs\Python\venv\Scripts\python.exe C:/Users/USER/AppData/Local/Programs/Python/venv
C:\Users\USER\AppData\Local\Programs\Python\venv\Scripts\python.exe: can't find 'main' module in 'C:/Users/USER/AppData/Local/Programs/Python/venv'

Please help me to solve this issue

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by santoshphilip** [comment]
Give me a day or two. I am traveling and don’t have my computer. 
At first glance, I am not see where the problem is coming from.
Are you using python2 or python3 ?

    On Monday, March 14, 2022, 08:05:25 AM PDT, Mohammad Zeyad ***@***.***> wrote:  
 
 


the code is

import sys

pathnameto_eppy = "C:/Users/USER/AppData/Local/Programs/Python/venv/Lib/site-packages/eppy"
sys.path.append(pathnameto_eppy)
from eppy import modeleditor
from eppy.modeleditor import IDF
iddfile = "C:/Users/USER/AppData/Local/Programs/Python/venv/Lib/site-packages/eppy/resources/iddfiles/Energy+V8_9_0.idd"
fname1 = "C:/Users/USER/AppData/Local/Programs/Python/venv/Lib/site-packages/eppy/resources/idffiles/V_8_9/test1.idf"
IDF.setiddname(iddfile)
idf1 = IDF(fname1)

idf1.printidf()

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mohammad-zeyad** [comment]
I used python 3.7 

I tried to install the main package in the command prompt, but it shows an error 

//
Command Prompt Window

C:\Users\USER>pip install main
Defaulting to user installation because normal site-packages is not writeable
Collecting main
  Using cached main-0.1.tar.gz (1.1 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: main
  Building wheel for main (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      running bdist_wheel
      running build
      running build_scripts
      creating build
      creating build\scripts-3.7
      error: [Errno 2] No such file or directory: 'main'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for main
  Running setup.py clean for main
Failed to build main
Installing collected packages: main
  Running setup.py install for main ... error
  error: subprocess-exited-with-error

  × Running setup.py install for main did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running install
      C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        setuptools.SetuptoolsDeprecationWarning,
      running build
      running build_scripts
      creating build
      creating build\scripts-3.7
      error: file 'C:\Users\USER\AppData\Local\Temp\pip-install-34rkbiyv\main_4084475e39c84a7c8e75b00818ee694b\main' does not exist
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> main

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
//

Also, I am trying to install the main package by using Pycharm Python Interpreter 
But it shows again an error.

**Comment by santoshphilip** [comment]
You should do 
pip install eppy
(pip install main will not work)
Try that and let us know how it goes. 
Santosh. 
    On Monday, March 14, 2022, 02:11:07 PM PDT, Mohammad Zeyad ***@***.***> wrote:  
 
 


I used python 3.7

I tried to install the main package in the command prompt, but it shows an error

//
Command Prompt Window

C:\Users\USER>pip install main
Defaulting to user installation because normal site-packages is not writeable
Collecting main
Using cached main-0.1.tar.gz (1.1 kB)
Preparing metadata (setup.py) ... done
Building wheels for collected packages: main
Building wheel for main (setup.py) ... error
error: subprocess-exited-with-error

× python setup.py bdist_wheel did not run successfully.
│ exit code: 1
╰─> [6 lines of output]
running bdist_wheel
running build
running build_scripts
creating build
creating build\scripts-3.7
error: [Errno 2] No such file or directory: 'main'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
ERROR: Failed building wheel for main
Running setup.py clean for main
Failed to build main
Installing collected packages: main
Running setup.py install for main ... error
error: subprocess-exited-with-error

× Running setup.py install for main did not run successfully.
│ exit code: 1
╰─> [8 lines of output]
running install
C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\setuptools\command\install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
setuptools.SetuptoolsDeprecationWarning,
running build
running build_scripts
creating build
creating build\scripts-3.7
error: file 'C:\Users\USER\AppData\Local\Temp\pip-install-34rkbiyv\main_4084475e39c84a7c8e75b00818ee694b\main' does not exist
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> main

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
//

Also, I am trying to install the main package by using Pycharm Python Interpreter
But it shows again an error.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by mohammad-zeyad** [comment]
Yes, I installed eppy before. After that, it shows the error in the main package.

**Comment by mohammad-zeyad** [comment]
I solved my issue. Thanks for your kind support.

**Comment by santoshphilip** [comment]
how did you solve it ?
What was the problem.

It would be useful to know in case it comes up again.

**Comment by mohammad-zeyad** [comment]
Yes sure. 

Actually, I put my main.py file inside the venv folder. I just put the main.py file outside the venv folder. Also, I have an error in my code. I just remove that error.
