### ISSUE TITLE
Delete a forgotten temporary folder

### ISSUE THREAD

**Issue by dragance106** [santoshphilip/eppy#414]
Hi! First of all, many thanks for a very useful software. As I needed to see how eppy actually runs E+ simulations (to check whether I need to save an idf object after adding new fields and prior to simulation), I noticed a small bug in eppy/runner/run_functions.py:
- in line 357, it creates an empty temporary folder to serve as run_dir, and
- in line 358, it changes the current folder to run_dir. Then
- in line 399, it changes back to the original folder, but
- it misses to delete the temporary folder. 
Hence what is missing is a new line 400 which will contain `shutil.rmtree(run_dir, ignoreErrors=True)`.

I checked this on my configuration (Mac OS X 12.2.1), temporary folders do get accumulated under a specific subsubsubfolder of /var/folders. Not much of an issue if you run a few tens or hundreds of simulations, but I do plan to run a few hundred thousands of them...

**Comment by santoshphilip** [comment]
Do you think you can fix this?
Make a pull request once you fix it. I'll merge into the master and make a release

**Comment by santoshphilip** [comment]
@dragance106 , I see your pull request.
Can you fork from the `develop` branch and make the pull request.
(instead of the `master` branch)

It looks like a simple change. I'll release as soon as I can since it looks like you need to use it soon.

Couple of details that we may have to follow up on.

- would be good to have a unit test that tests the changes you made.
    - the unit tests for the run functions are tricky to write.
    - I may have to do it
- Your name has to be on the credits and in the copyright (acknowledges your contribution)
- We can do this later. I'll open new issue to make this happen, just be expidient with the new release

**Comment by santoshphilip** [comment]
@dragance106 , my apologies for the delay in merging your pull request.
I have merged into the develop branch.

I think it is important to add your name to the authors list.
Even though the change was small, it was not an easy one to find. It would have led to hard to fix errors if it was not fixed.

I'll open a new issue and give you instructions on where to add your name.
Pleas reply to this comment, so I know you got it

**Comment by dragance106** [comment]
Got the comment, Ok to add the name.
