### ISSUE TITLE
Objects which don't have Name as their identifier can't be selected using `getobject`

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#51]
For most objects, the first field which serves to identify them uniquely within their object type is called `Name`.

For `ZoneHVAC:EquipmentConnections` the identifier is `Zone_Name` which is not picked up by the `getobjects()` function.

There are potentially two ways around this:
1) Have an optional parameter which defaults to `Name` but can be overridden with `Zone_Name` or whatever the identifier is
2) Look for the first item in the object as that is always the identifier

I have a rough implementation of option 2, though there may be a nicer way of doing it:

```python
def getobject(bunchdt, key, name):
    """get the object if you have the key and the name
    retunrs a list of objects, in case you have more than one
    You should not have more than one"""
    # TODO : throw exception if more than one object, or return more objects
    idfobjects = bunchdt[key]
    try:
        id_field = idfobjects[0].objidd[1]['field'][0]
    except IndexError, e:
        return None
    id_field = id_field.replace(' ', '_')
    theobjs = [idfobj for idfobj in idfobjects if idfobj[id_field].upper() == name.upper()]
    try:
        return theobjs[0]
    except IndexError, e:
        return None
```

**Comment by santoshphilip** [comment]
This bug did bite me last week.

I made the same mistake when writing IDF1.newidfobject() in modelbuilder.py. I was coding under the impression that all idfobjects have the Name field.

I fixed it there. (do a search for the string "backward compatibility" in ./eppy/modelbuilder.py)
Something similar may be possible here ?

**Comment by jamiebull1** [comment]
Ok, so to fix it should I start a new branch (say `i51_uniqueidentifiers`) from the master branch, or from the develop branch, or somewhere else? I'm not totally clear on the release cycle/patch cycle you're using. I'm assuming fairly ad hoc with things getting merged as and when they're ready?

**Comment by santoshphilip** [comment]
In theory develop branch is where the new branch should come from. My thinking on this:
- master
    - release version
- develop
    - the latest and greatest, but pretty stable and usable
- ixx_issuename
    - branch from **develop** to work on a feature
- ixx_bugfix (for critical bugs)
    - branch from **master** to fix the bug. 
    - merge into **master** to release bugfix
    - merge into **develop**

Having said that **develop** branch may not be ready at the moment. There are large superficial changes in the code. This is because I ran pylint on all the code as a step to making a python3 release. This happened in branch **develop_lint_3k**. Branch **develop_lint_3k** now has working python3 code in folder "p3". 

Branch **develop_lint_3k** may not have been merged into **develop** branch  yet. I need to check. It would be good do your branch from **develop** after **develop_lint_3k** has been merged into **develop**. There will be less likelihood of merge conflicts at that point.

I'll let you know as soon as **develop** is updated

**Comment by jamiebull1** [comment]
Ok, that's clear enough. I'll keep an eye out then.

**Comment by santoshphilip** [comment]
Branch **develop** has been updated and passes all pytests
do:
- git checkout develop
- git branch i51_uniqueidentifiers
- git checkout i51_uniqueidentifiers

**Comment by jamiebull1** [comment]
This is fixed and ready to be merged back into `develop`. All tests are passing, including a new test case created to catch this issue if it crops up again.

**Comment by santoshphilip** [comment]
The fix looks good.
I'll merge it into develop and close this issue

**Comment by jamiebull1** [comment]
Ok to close this now?

**Comment by santoshphilip** [comment]
It has been merged into develop.
I'll close it
