### ISSUE TITLE
Results extraction and processing

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#59]
I was wondering whether it might be worthwhile to add some functionality to Eppy, along the lines of the HTML table parser, but reading the CSV/SQL outputs. Currently we're limited to the tables produced by EnergyPlus but we could potentially put together a simple API to extract other outputs as well.

Does anyone have any thoughts on this, or on what the API should look like?

**Comment by daren-thomas** [comment]
huh... I guess this might be the place to plug my esoreader module:
https://github.com/architecture-building-systems/esoreader

while it has a low-level api that sort of maps the way an eso file is
structured, it also has a high-level api for viewing the timeseries data
produced as pandas dataframes.

that's right. pandas dataframes. check out the github page, it has a short
tutorial.

**Comment by jamiebull1** [comment]
That looks a lot like what I do myself. I'm a massive pandas fan! Replacing pandas with numpy may be faster though, given the more limited operations needed. I'm on the road at the moment so will have a better look when I get to a desk. Thanks for the pointer.

**Comment by santoshphilip** [comment]
My first reaction is, can i import it into eppy?
I am on the road. Cannot explore this yet :-(


Sent from my iPhone

**Comment by santoshphilip** [comment]
I saw this issue opened just before i got on a long flight.
So had some time to think

today we can do

    building = idf.idfobjects['BUILDING'][0]
    print building.Name

How about this

    print idf.results.cooling
    print idf.results.heat_rejection

Functions from readhtml will do the actual data extraction
We can also have

    mrt =  idf.results.zone1.hourly.MRT
    # mrt might be a list coming from the ESO file ?

If we can import esoreader and the API allows it, we can use functions from esoreader to do this

**Comment by daren-thomas** [comment]
while I definitely think you can import the esoreader and provide this
functionality, I'm not quite sure why you would want to do this.

Maybe I don't understand.

So far, I have always thought of the eppy library as specialized in reading
and manipulating IDF files. That is, creating INPUT for EnergyPlus.

I wonder if you would end up diluting the API (do one thing and do it well)
by adding on OUTPUT from EnergyPlus.

**Comment by santoshphilip** [comment]
Darren,
    You make a very good point, that I will try to address here

eppy is a scripting language for E+.
I see simulation as a process where inputs and outputs make the entire model.
So a scripting language for should be able to access the entire model, both input and output.
Allowing access to the entire model will allow you to take steps like the following:

    # untested code
    if idf.results.cooling > tippingpoint_c:
        for window in largewindows:
            window.construction = good_SHGC

    if idf.results.heating > tippingpoint_h:
        for window in largewindows:
            window.construction = good_UValue
            
The motivation to being able to read outputs, is being able to go back and forth between input and output. Having the outputs affect the inputs for the next run. 

This has not been apparent in the present version of eppy, since the htmlreader in eppy is **brain dead**. The output API really sucks. This is starkly  apparent in contrast to the input API

I did not have a design for the output API until this issue was opened. Following the discussion here gave allowed me to come up with the seeds of an API design, that shows signs of being powerful. So thank you for this discussion.

----------------------------

I think we agree on the fundamentals here

I like the simplicity of the UNIX philosophy. to quote from the [developer documentation of eppy](http://pythonhosted.org/eppy/dev_docs/phil_eppy.html#)

*The Philosophy of eppy alludes to the Unix Philosophy. The philosophy of eppy takes inspiration from the Unix Philosophy, that speaks of doing one thing and doing it well. Unix has the tradition of having small tools that do a single thing. A number of tools can be stitched together to do a more complex task. Of course, since eppy is written in Python, it adheres to the “Zen of Python”*

You allude to this by saying

*I wonder if you would end up diluting the API (do one thing and do it well) by adding on OUTPUT from EnergyPlus*

If eppy were to only one thing well, it should be this:
from [dev docs - Idd file and eppy](http://pythonhosted.org/eppy/dev_docs/phil_eppy.html#idd-file-and-eppy):

*At it’s heart, eppy is simply a scripting language that puts the idd and idf file into a python data structure. Then it uses the power of python to edit the idf file.*

eppy uses the intelligence embedded within the IDD for all it's functionality. This allows eppy to work with all versions of E+, both past, present and future, those yet to come.

Note that IDD file does not have the embedded intelligence to build an HVAC system. The IDD file also does not give you the structure of the output. But as a user, I want to be able to write scripts that engage the HVAC system as well as the outputs. And I want to back and forth between inputs and outputs

So here I cheat on the unix philosophy and pull the *Zen of python*  card:
- practicality beats purity


I would like to structure eppy so that it really does only IDF editing using IDD knowledge.
Reading outputs and HVAC building should be separate packages. My strategy for now is to push these external pieces into eppy for now, and then pull them out as a separate package later. I am willing to break backward compatibility a little until we reach version 1.0. Although we have managed development without breaking backward compatibility so far. 

None of this is set in stone. It will evolve as development continues

**Comment by jamiebull1** [comment]
In terms of the implementation of esoreader, I like the ability to make a substring match of the variable you're interested in and can see how that comes into its own in an iPython notebook. The difference between the esoreader API and the one Santosh sketched out is making the `heating`, `cooling` and any other variables behave like attributes of a `results` object. That makes it behave like eppy does, presumably by using an overridden `__getattr__` method. (@santoshphilip, would this require `bunch`?)

So we're talking about replacing/syntactically sugaring the `df = eso.to_frame('heating')` with `df = eso.heating` and similar, which I think is a much cleaner API. Is that something you'd like to see in esoreader @daren-thomas , or is a third API a step too far in terms of maintainability? It's certainly not in keeping with *"There should be one-- and preferably only one --obvious way to do it."*

The/an alternative is to `import esoreader` and add the eppy-style API as a wrapper within eppy.

And taking a step back for a moment, if I'm understanding this properly, what you're suggesting Santosh, is to have as a version 1.0 goal a larger program with the following skeletal structure:

```
- building energy sim interface which uses (at least) the three items below
-- eppy (core functionality as described by Santosh above)
-- hvacbuilder (split out from eppy)
-- esoreader (potentially wrapped, as the results handler)
```
Does that seem like a reasonable architecture to keep in mind (subject to evolution)? Seems nice and simple to me.

**Comment by daren-thomas** [comment]
I think I now understand better what you want to achieve and I am flattered
you took the time to address my point. Thank you.

The license of the esoreader project is "MIT", so you could do both - keep
the esoreader as a dependency and import it, or actually ship it with eppy
(my boss would like some kind of reference to his chair as per the license
if you do this).

Either way you choose, you will probably not want to use the pandas API,
but the lower level API that basically just reflects the structure of the
eso file. I think I might have taken a shortcut when parsing the file in
that the timestamps do not get parsed into the the resulting structure -
something that I would be glad to fix if this is needed, but that would
require using a datastructure like the pandas timeseries as opposed to just
plain python arrays.

We can also discuss changes to esoreader to make it easier to use for eppy
if you like. Either way, parsing eso files is not such a big deal anyway -
eppy could even just roll its own! I'd just love to see some of my work
contributing to a project that has helped me a lot in the last few months :)

Best,
Daren

**Comment by santoshphilip** [comment]
Darren, Jamie,

Thank you for your responses. This has been a very encouraging discussion. I have been traveling with a lot of down time. So I had time to think about this

But first let me respond to your comments.

Darren, I agree that eppy would use the lower level API. We can decide whether it should be embedded or imported. When the time comes, we can follow licensing requirements. (You may have to remind me)

Jamie, `bunch` may be the easiest way to get to the dot notation that eppy uses, but I am not wedded to it. (`bunch` overrides `__getattr__` for you) Regarding the larger program structure, I am keeping it vague for now, mostly so that I don't get mentally locked into one way of seeing things. Your description is a reasonable take on it


Coming back to the topic of results and outputs. Some of the E+ outputs are:
- HTML tables
- csv files
- sql files
- eso files
- rdd files

I see results module broken up in the following way:
- reader
- wrapper

The "reader" reads the output data into a python data structure. There will be some fairly straight forward coding here, using appropriate library (sqlite3, csv, beautifulsoup etc). Some smart thinking will have to be done while designing the python data structure. The "reader" may be embedded in eppy or maybe an external package that is imported. At this point, even without the "wrapper", we have a useable results module. 

The "wrapper" wraps it into a dot format that eppy uses. 

I am drawn into this way of structuring, because of the input API of eppy is written this way. [Underlying Data Structure of eppy](http://pythonhosted.org/eppy/dev_docs/data_eppy.html) describes some of this. This was a historic accident rather than intentional, but worked out pretty well. 

I have a couple of motivations for using esoreader in eppy
- I would like to see an "ecosystem" of open source software that support each other in the energy modeling world.
- using esoreader in eppy will encourage and support Darren in his development of esoreader.
- over time we may develop a protocol for how the packages in the "ecosystem" work with each other. This may just be some informal rules. 

I am saying this without looking deep into esoreader code. From Jamie's and Darren's responses, it looks like esoreader is a viable candidate for eppy to use.

---------------------

#### Other ideas
eppy will be significantly more powerful with the following api call

    idf.run()
    
This will basically run the idf file. So we can do things like:

    # untested code
    def reduce_cooling():
        """reduce cooling by increasing SHGC"""
        if idf.results.cooling > tippingpoint_c:
            reached_tippingpoint = False
            for window in largewindows:
                window.construction = improveSHGC(window.construction)
                # improveSHGC will improve the SHGC in the construction
        else:
            reached_timmpingpoint = True
        return reached_timmpingpoint
    
    reached_timmpingpoint = False
    idf.run()
    while not reached_timmpingpoint:
        reached_timmpingpoint = reduce_cooling()
        if reached_timmpingpoint:
            break
        else:
            idf.run()

I know there are other tools that will let you do something similar, but this single function `idf.run()` can really change the nature of eppy.

What is interesting is that `idf.run()` should be configurable so that:
- It can run locally on your machine
- can run on a remote machine
- can run on the cloud
- can be run by a third party service ( [apidae ?](https://apidaelabs.com) )

At present eppy does not know that a run is completed. E+ should be able to send a signal back to eppy so that the loop can continue.

I should probably open a new issue on this

**Comment by santoshphilip** [comment]
### Next steps

Continuing with the idea of organizing the results module into "reader" and "API wrapper"

htmlreader
- HTML table already has a comprehensive "reader" in readhtml.py
- Santosh will work on the "API wrapper" for readhtml that is more eppy-ish
- this will help us figure out how to be more eppy-ish in the results module

esoreader
- Darren and/or Jamie will work on a eso "reader" for eppy
    - preferable this should be simple import/embed of Darren's esoreader with minimal changes to esoreader.
    - some example code to show how the "reader" will work in eppy
- My preference is to have Darren work on this. So, some comments to Darren
    - As they say in the movie, "Your mission Darren, if you choose to accept it ..... "
    - you already own this. So it is easier for you to work on this 
    - there is no time schedule. It gets done when it gets done.
    - It does not have to be perfect. it just has to work, even badly.
    - We will incrementally improve it.

If Darren and Jamie are unable to work on this, Santosh or Eric may be able to pick it up

We'll talk about documentation when there is working code.

**Comment by daren-thomas** [comment]
I'm in. I'll start planning as soon as i get back from my summer vacation.

**Comment by jamiebull1** [comment]
That sounds good to me. I've been doing a lot of wrapping up of EnergyPlus runs in Python over the past few years so the idf.run() part would be a great thing for me to work on. I don't have much time over the next week or so but I'll give it some thought. If you want to start a new issue for that Santosh, that would be good. I'll look for it when I'm back.

**Comment by santoshphilip** [comment]
Darren, Jamie,
This is great news. I am still traveling. I'll take the next steps as soon as I am back.

**Comment by santoshphilip** [comment]
Darren, Jamie,

I am glad both of you are taking on this. Both the areas are outside my area of expertise and I am happy to have eppy grow beyond my skillset.
I'll open two issues on these two tasks. My next post will point to them and suggest branch names to work with.

Darren,
- `readhtml.py` is the only results module in eppy right now. 
- I am going to reorganize the file structure in the following manner:
    - create a folder `results` with a `__init__.py` file in it.
    - move `readhtml.py` into the `results` folder
    - So we will have to access `readhtml` by `import eppy.results.readhtml` rather than `import eppy.readhtml`
    - I'll update the documentation to reflect this change
- Your eso reader functions will go inside the `results` folder.

Some thoughts on the coding:
- eppy is python3 compatible (the python3 code is in the p3 folder and it passes all the unit tests). the python3 version is not production ready yet, meaning, it does not install with `pip install`
- to keep it python3 compatible you need to take the following steps:
    - run [pylint](http://www.pylint.org) periodically on your code.
         - pylint can be a little too detailed (anal is the right term I think). You may want to ignore some of it's comments.
    - Put the following lines at the top of the file as the first imports (see other files in eppy):
    
        `from __future__ import absolute_import`
        `from __future__ import division`
        `from __future__ import print_function`
        `from __future__ import unicode_literals`

- Eric Youngson is the "python3 release master". When the time comes, he will work with you to ensure that the python3 version works. The process is quite automated, and usually works on the first try.
- Apart from that, I'll let you take the lead on this. 

Jamie,
- I'll make a folder `runner` with `__init__.py` in it.
- you can put in the `run` functions within that folder
- I understand that the `run` functions are going to trigger external programs. You may need to break the structure and organization of eppy to make this happen. Go ahead and do so. We'll find a way of walking out of it later.
- My comments above about python3 compatibility apply
- I assume you will focus on any one platform (windows platform ?). We'll worry about the other platforms later.

**Comment by santoshphilip** [comment]
Issues opened at 
https://github.com/santoshphilip/eppy/issues/61
and
https://github.com/santoshphilip/eppy/issues/62

**Comment by JasonGlazer** [comment]
I am just catching up on this thread. I agree that making eppy cover input, output and running simulations would be great. It is a logical next step. 

For my ASHRAE project, I am already modifying some inputs based on output. In general, I have been sticking to the tabular XML file which mirrors the HTML file but uses XML (OutputControl:Table:Style, XMLandHTML) and then just using xml.etree.cElementTree. Very easy. 

I am also running EnergyPlus by just doing a subprocess.call() to a string pointing to the RunEPlus.bat file with arguments. Probably not too portable.  I don't know if you are aware but EnergyPlus 8.3 added command line arguments, try typing "energyplus --help".

**Comment by JasonGlazer** [comment]
Pondering this some more, we should make sure API works well for groups of input files, their simulations, and their associated output files. I believe what has been described so far will work fine but it would be good to think about use cases of multiple simulations and comparing between them since that is what building energy modeling is all about.

**Comment by jamiebull1** [comment]
Hi Jason. Thanks for the comments and the tip about the changes to the command line options in 8.3. I saw a mention of this on UnmetHours yesterday so it was on my radar. 

I'm away now for about a week but if you have any more thoughts on running EPlus in Eppy Santosh has started a thread for that. It would be great to have your input.
