### ISSUE TITLE
Python3 pip install

### ISSUE THREAD

**Issue by lafrech** [santoshphilip/eppy#64]
As of https://github.com/santoshphilip/eppy/issues/39, eppy is fully functional in Python3.

Making it available through pip would be great.

**Comment by santoshphilip** [comment]
eayoungs had volunteered to take ownership of the python3 release and maintainance.
I have assigned this issue to him

**Comment by santoshphilip** [comment]
Jerome,
How urgent is it to have the pip install up and running
I know enough to get "pip install eppy3" working quickly as a temporary measure.
Let me know if you need it and I can get it up in a few days

In the long run "pip install eppy" should automatically install the right version of eppy depending on the python version. I believe this is straightforward. Just have not gotten to it yet.

**Comment by Jerome-github** [comment]
> I know enough to get "pip install eppy3" working quickly as a temporary measure.
> Let me know if you need it and I can get it up in a few days

Don't bother. We don't expect to release anything publicly before months. As developers, pip install is a convenience but not mandatory at all, manual install does the job.

Thanks.

**Comment by eayoungs** [comment]
I'll take a look this weekend.

**Comment by santoshphilip** [comment]
Eric,
    Don't start on it yet. 
I need to give you some background on it. 

Santosh.

**Comment by eayoungs** [comment]
OK. I'll focus on cleaning up issue #30

**Comment by santoshphilip** [comment]
Eric,
   The present python3 version was done mostly to prove that eppy will work in python3. I'll document how it is done at the present moment. You task would be to research and find the best way to do the conversion on an ongoing basis with every release. Let me know whenever you are ready to start on this and I'll try to complete my documentation by then.

**Comment by santoshphilip** [comment]
Eric,
    From our discussions yesterday. There are two primary tasks for this issue:
    
1. Install correct version of eppy with `pip install eppy`
-------------------------------------------------------

- When using python3, install the python3 version of eppy
- When using python2, install the python2 version of eppy

The upload to [pypi/eppy](https://pypi.python.org/pypi/eppy/) has to be updated to make this happen. At this point I don't know what it takes to do this. Your task is to figure that out and implement it. Make a temporary project on PyPi to explore this. We don't want `pip install eppy` to break while you are figuring things out

2. Workflow for development
------------------------

For the forseeable future, eppy development will continue in python2. Once eppy is ready for a release, the following things should happen:

- all test in python2 should pass
- python3 version should be generated
- all test in python3 should pass
- a package should be uploaded to PyPi so that `pip install eppy` will install the latest version.

The workflow by which this should happen is not clear to me yet. I would like you to explore the possibilites. Find out how existing packages do this. Don't reinvent the wheel - borrow/steal whenever you can.

**Comment by santoshphilip** [comment]
Eric,
I have merged branch `eayoungs` into branch `develop`
- some cleanup was done
- all tests are passing with in python2 and python3, with and without numpy
 
merge this into branch `i64_python3` and work on this issue #64

**Comment by santoshphilip** [comment]
Eric,
I figured out why we were having trouble when running `2to3sh.sh` when you were at my office.
- the problem that it was creating an extra folder `./eppy/p3/p3`
- this was happening because we were running `2to3sh.sh` from `./eppy`
- run `2to3sh.sh` from `./eppy/eppy` (there is an `2to3sh.sh` in that folder) and all will be well

**Comment by santoshphilip** [comment]
@eayoungs I was at a python meetup a few days back and got some good advice on packaging and installing python 2 and python 3. 
Take a look at this stack overflow question [How to organize Python modules for PyPI to support 2.x and 3.x](http://stackoverflow.com/questions/2398626/how-to-organize-python-modules-for-pypi-to-support-2-x-and-3-x). It addresses how to use `pip install eppy` can install the appropriate version of eppy

**Comment by jamiebull1** [comment]
+1 that looks like a good approach

**Comment by eayoungs** [comment]
@santoshphilip : Thanks for following up with the folder issue. I am just getting back to all this now; work & all. :-D

- I'm reviewing the article on organization now...

**Comment by jamiebull1** [comment]
Closing this since we're going the `six` route #100
