### ISSUE TITLE
Exception raised when calling `IDF.initread`

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#81]
I was having a look at the functions in `modeleditor`, trying to get coverage up a bit higher so if we do want to streamline the various `IDF` classes into one then we have a good safety net to catch us. While doing this I realised I was getting errors when trying to use the `initread` method. `initreadtxt` is unaffected. The traceback is:

	============================= ERRORS =============================
	File "C:\Users\Jamie\git\eppy\eppy\idfreader.py", line 114
	AttributeError: 'Eplusdata' object has no attribute 'dt'
	def test_initread():
			"""Test for IDF.initread().
			"""
			idf_name = "../resources/idffiles/V_8_0/smallfile.idf"
			idf = IDF()
	>       idf.initread(idf_name)

	File "C:\Users\Jamie\git\eppy\eppy\tests\test_modeleditor.py", line 640

	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
	File "C:\Users\Jamie\git\eppy\eppy\modeleditor.py", line 703
	in initread
		self.read()
	File "C:\Users\Jamie\git\eppy\eppy\modeleditor.py", line 544
	in read
		commdct=self.idd_info, block=self.block)
	File "C:\Users\Jamie\git\eppy\eppy\idfreader.py", line 186
	in idfreader1
		convertallfields(data, commdct)
	_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

	data = <[AttributeError("'Eplusdata' object has no attribute 'dt'") raised in repr()] SafeRepr object at 0xfb50ec8>
	commdct = [[{}], [{}], [{'format': ['singleLine'], 'memo': ['Specifies the EnergyPlus version of the IDF file.'], 'unique-object... method.', 'Refer to InputOutput Reference and Engineering Reference for more information'], 'type': ['choice']}], ...]

		def convertallfields(data, commdct):
			"""docstring for convertallfields"""
			# import pdbdb; pdb.set_trace()
	>       for key in data.dt.keys():
	E       AttributeError: 'Eplusdata' object has no attribute 'dt'

	File "C:\Users\Jamie\git\eppy\eppy\idfreader.py", line 114
	AttributeError

This is also showing up in the docs [here](http://pythonhosted.org/eppy/newfunctions.html#blank-idf-file).

**Comment by santoshphilip** [comment]
I'll take a look. 
Should I be looking at develop branch or master branch. 

Santosh.

**Comment by jamiebull1** [comment]
Definitely an issue on the develop branch. I assume also on the master branch if that's where the docs are coming from.

**Comment by santoshphilip** [comment]
FYI
The docs are coming from a jupyter notebook
That is how I make most of the documentation.

`cd ./eppy/docs`
`jupyter notebook # or ipython notebook`

will show all the all notebooks that become the docs.

I am looking thru all of this right now. 
Lots of code I don't really remember :-)

**Comment by santoshphilip** [comment]
Jamie, I ran the following code fro `./eppy` in the `develop` branch

    from eppy import modeleditor
    from eppy.modeleditor import IDF
    fname = "./eppy/resources/idffiles/V8_0_0/5ZoneSupRetPlenRAB.idf"


    idf = IDF()
    idf.initread(fname)

    idfnew = IDF()
    idfnew.initnew()

    txt = open(fname, 'r').read()
    idffromtxt = IDF()
    idffromtxt.initreadtxt(txt)

It runs fine.
Meaning I am not able to recreate error.
(I thought I was getting the error when i started)

**Comment by santoshphilip** [comment]
About the error in the docs, I ran the notebook again in `develop` and in `master`. The apparent error is some old artifact. I does not appear when I run the code in the notebook

**Comment by jamiebull1** [comment]
I'm still seeing the error. Can you see any reason why that might be from the diff [here](https://github.com/santoshphilip/eppy/compare/develop...jamiebull1:modeleditor_tests?expand=1)?

**Comment by jamiebull1** [comment]
It does run fine for me from `./eppy` but not in the test suite.

**Comment by jamiebull1** [comment]
Ok, it looks like there were a couple of errors there. One is that I had the wrong path and should have been looking at `../eppy/resources/...` not just `../resources/...`. However I had tried with that and was still getting the same error.

It turns out that the test only passed with that path if I also specify that the path name is a base `b'string'`. Passing a raw `r'string'` a unicode `u'string'`, or just a `'string'` all fail with the `AttributeError: 'Eplusdata' object has no attribute 'dt'` error.

I've changed the tests for `str` in `Eplusdata.__init__()` to be tests for `basestring` and all tests are now passing.

**Comment by santoshphilip** [comment]
@jamiebull1 
You have been working in tricky part of the code. Also you have run into a nasty problem that unit testing has. Most people discover it by running into it.

Unit test does not play well with reading or writing files on disk. Once you set a path name, you find you cannot run the unit test from other folders. When your write tests fail, it leaves files scattered on the disk. Since the test failed, the cleanup is not done. The test code also winds up being very fragile. You cannot move files or folders around, Everything breaks
    
The standard solution to this is not use file name, but to use file handles in the functions you are testing. 
    
So you would not write the following function:

    def readafile(filename):
        return open(filename, 'r').read()
        
instead you would write:

    def readafilehandle(fhandle):
        return fhandle.read()

    # write unit test for readafilehandle
    def test_readafilehandle():
       import StringIO
       txt = 'hello'
       fhandle = StringIO.StringIO(txt)
       assert readafilehandle(fhandle) == 'hello'

    fhandle = open(filename, 'r')
    txt = readafilehandle(fhandle)
        
Often eppy's code does not cooperate with this kind of unit testing.
So when I write unit tests, I have wind up rewriting the functions so that they use file handles. But there are times you really need functions that use filename :-(

I have not found any good solutions for unit testing actual reads and writes to the disk. I have some ideas on how to do it without making the tests too fragile, but they are kind of ugly.

Sorry I did not flag you on it early enough. I had forgotten what a problem this was with unit test. If you google "python unit tests and IO", you will see others complaining about this.

So what do we do now ?
I have not thought that far. Let us give it a few days and maybe the next steps will present themselves :-)

**Comment by jamiebull1** [comment]
Ok, thanks for the advice @santoshphilip.

So in summary, what we need (in addition to good test coverage) is:

1. Repeatable tests that work for both Python 2 and Python 3
2. Not to clutter up the filesystem with the results of failed tests
3. No other side effects such as changing working directory
4. Really test IDF read and write functions

Options that satisfy those conditions:

1. Repeatable tests that work for both Python 2 and Python 3

- Don't access any resources by location
 - Read from `snippets` and write/read back using filehandles
 - Read from `snippets` and write/read back using `curdir`
 - Read from `snippets` and write/read back using a `tmpdir`
- Find the resources location
 - Use `os.walk` starting from `pardir` and work back up the directory tree. This is slow and ugly!
 - Have the `resources` directory duplicated in `p3` so it's in a known location
 - Save the generated p3 at the same directory level as eppy and use directory traversal (I usually use a flat directory structure which is probably why I've never had much trouble with this before)

2- Not to clutter up the filesystem with the results of failed tests

- Don't write anything to the filesystem
 - As with filehandles
- Tidy up after running tests
 - Wrap each test with a `try: except: finally:` block
 - Use the builtin `teardown` fixture method as provided in `pytest`, `unittest`, etc.

3- No other side effects such as changing working directory

- Don't change the working directory
 - As with filehandles
- Ensure the working directory is set back after any change
 - Wrap each test with a `try: except: finally:` block which provides setup and teardown
 - Use the builtin `setup` and `teardown` fixture methods as provided in `pytest`, `unittest`, etc.

4- Really test IDF read and write functions

- Actually do IO on files
 - Use one of the options above
 - Or don't and accept that testing can stop short of really writing to a location

My preference is to use a combination of the `snippets` for most tests as you already have, and `setup(method)`, `teardown(method)` and `tmpdir` for a limited number of "real" tests to cover item 4.

This also isn't far from what I have in the latest PR. I won't do any more on this until I know your thoughts though.

**Comment by santoshphilip** [comment]
@jamiebull1 , Your comments on testing are right on the ball.

I am setting up some general direction on testing here. Some of it is driven by having to maintain clarity. This clarity is important especially in communication to other developers who may come on board

So the present thinking on unit testing
- use unit tests (pytest) when there are no external dependencies
- use integration tests when there are external dependencies

known external dependencies:
- IO operations (read and write to disk)
- running Energyplus from eppy
- find location of Energyplus (preferably latest Energyplus)
- find location of IDD file

Right now eppy does not have any integration tests. We can jury rig something for the moment. For the long term, some thought needs to be put into this.

Function with IO operations can be tested without invoking the IO operations.
For the moment let us do the following for functions with IO operations
.- write the function so that it can take the filehandle or file name as an argument
- while unit testing, use the filehandle
- don't test with filenames in unit tests

rewritten function and test may look like this (reiterating what was in the previous post) :

    def changetxt_orig(fname, change):
        txt = open(fname, 'r').read()
        return change + txt
        
    def changetxt_alter(fname, change):
        try:
            txt = open(fname, 'r').read()
        except TypeError as e:
            # it is not a file. Assume it is a file handle
            fhandle = fname
            txt = fhandle.read()
        return change + txt

    def test_changetxt_alter():
        origtxt = "spam"
        change = "not "
        newtxt = "not spam"
        import StringIO
        filehandle = StringIO.StringIO(origtxt)
        result = changetxt_alter(filehandle, change)
        assert result == newtxt
        
Some of the eppy test need large text snippets. Keeping these text snippets in the test modules will clutter it up. `snippet.py` is a good place to keep them. The idd file is extremely large. The iddfile can be imported from `iddcurrent.py`

I am still researching how to set up a process for doing integration tests. At least looking at how others do it. Will write further on it once I have some clarity. @jamiebull1  if you have any insight into this, I would like to hear

Next steps:
- update tests for functions with IO operations so that they use filehandles
- for the moment we will not have tests that write to the disk.

Hopefully I'll quickly come up with a strategy for doing integration tests

**Comment by jamiebull1** [comment]
@santoshphilip 

A few thoughts then.

We could keep the integration tests separate by having the integration tests in a separate test folder which is explicitly excluded from the default test suite. There are two classes of integration tests that I see.

 - OS dependencies: file IO, system paths
 - external software dependencies: EnergyPlus

Of those, the first one isn't a problem to test in CI for Windows and Linux, though we don't have a solution on Mac yet. The second part is the hard part, since it requires installing EnergyPlus on the CI servers for each run, and as far as I'm aware the installers are still hosted behind a password. I'd ideally like to test against the current release version, the last version and the development version, but just the current version would be a big improvement. I'll have another look into this as I'm sure I remember someone at NREL mentioning that they would be removing the password (in the context of dockerfiles I think).

**Comment by jamiebull1** [comment]
Closing this as the only outstanding part is covered by #85

**Comment by danielmcquillen** [comment]
Just a note : this error also shows up if you're using pathlib and accidentally pass in a PosixPath instance rather than the string representation of it. Hope that saves someone some time.
